name: Install and Test

on:
  pull_request:
    branches:
      - develop
      - production

jobs:
  test-client-app:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client-course-schedulizer
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm ci
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: |
          npm test
        working-directory: ${{env.working-directory}}
